from BasicImports import *
def intro():
    PlaySound(intromusic, SND_ASYNC)
    print_slow("This is the story of our past. Your past.\n")
    print_slow("In the beginning there was Light and Darkness.\n")
    print_slow("The light was followed by those that seeked to do good.\n")
    print_slow("But those that didn't fell into the darkness...\n")
    print_slow("Overtime the darkness grew stronger. Feeding on the weak.\n")
    print_slow("Once the darkness became powerful, it created a race of Dreg Lords.\n")
    print_slow("The Dreg Lord's created havok among those in the light.\n")
    print_slow("Overtime the Light started to dwindle to a flicker.\n")
    print_slow("But that flicker stayed bright, and manifested in someones heart.\n")
    sleep(1.5)
    print_slow("This is your heart.\n")
    sleep(1)
    print_slow("You are the one that will bring balance to the world.\n")
    sleep(2)
    print_slow("But it will not be easy.\n")
    sleep(3)
    print_slow("Make sure to never forget.\n")
    sleep(2)
    print_slow("You are the light.\n")
    sleep(5)
